stages:
  - docker

.docker:
  stage: docker
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  only:
    - tags
  before_script:
    - echo -n "${CI_REGISTRY_PASSWORD}" | docker login --password-stdin -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}"

.docker_build: &docker_build |
  docker build --pull --no-cache --rm --build-arg NGINX_VERSION="${NGINX_VERSION}" -f Dockerfile -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" .

.docker_push: &docker_push |
  docker push "${CI_REGISTRY_IMAGE}"

docker_build:
  extends: .docker
  script:
    - *docker_build
  except:
    - tags

docker_build_and_push:
  extends: .docker
  script:
    - *docker_build
    - *docker_push
  only:
    - tags
