version: '3.8'

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - NGINX_VERSION=1.20.2-alpine
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
