name: Docker

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          nginx_version: ['1.20', '1.21', '1.22', '1.23']
    steps:
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            NGINX_VERSION=${{ matrix.nginx_version }}
          push: true
          tags: |
            richardboldis/nginx:latest
            richardboldis/nginx:${{ matrix.nginx_version }}-${{ github.ref_name }}
            ghcr.io/richardds/nginx:latest
            ghcr.io/richardds/nginx:${{ matrix.nginx_version }}-${{ github.ref_name }}
